name: bill desk

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999999

    steps:
    - name: Download Ngrok & NSSM 
      run: |
        Invoke-WebRequest https://drive.google.com/file/d/1k_glvajAd6dHvKwZrDUX7XgGnWHn3MNy/view?usp=sharing  -OutFile ngrok.exe
        Invoke-WebRequest https://drive.google.com/file/d/1ZtuEdVs4TTKI8Gzdg1d-TV-xjT1iGljs/view?usp=sharing  -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://drive.google.com/file/d/1kbzkZ2JHrTxWj37H3K00kZdG-DfHoh-x/view?usp=sharing  -OutFile NGROK-AP.bat
        Invoke-WebRequest https://drive.google.com/file/d/1qUR9RYjt7bM7hv4ojXW6FC-lX86qcRTj/view?usp=sharing  -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://drive.google.com/file/d/1xwgRdeJqi-o5L6zcw1cvbDOgOWemlRNw/view?usp=sharing
    - name: Make YML file for NGROK.
      run: start NGROK-AP.bat
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP CPU 8 Core - 32GB Ram - 255 SSD.
      run: cmd /c NGROK-CHECK.bat
    - name: All Done! You can close Tab now! Maximum VM time:60h.
      run: cmd /c loop.ps1
